# Quick Guide -  Dataframe Creation

## Pandas Create Dataframe Syntax

pandas.DataFrame(data, index, columns) 

**Parameters:** 
    * data: It is a dataset from which a DataFrame is to be created. It can be a list, dictionary, scalar value, series, and arrays, etc. 
    * index: It is optional, by default the index of the DataFrame starts from 0 and ends at the last data value(n-1). It defines the row label explicitly. 
    * columns: This parameter is used to provide column names in the DataFrame. If the column name is not defined by default, it will take a value from 0 to n-1. 

**Returns:**
* DataFrame object

In [18]:
# Import pandas library
import pandas as pd

### Creating an Empty DataFrame

In [21]:
# Create an empty DataFrame and Storing it in variable df
df = pd.DataFrame()
 
# Print dataframe
print(df)

Empty DataFrame
Columns: []
Index: []

## From Lists

### Creating  Dataframe from Lists

In [26]:
# initialize list elements
data = [10,20,30,40,50,60]

# Creating the pandas DataFrame with column 'Numbers' 
df = pd.DataFrame(data_m1, columns=['Numbers'])
 
# Displaying DataFrame
df.head()

   Numbers
0       10
1       20
2       30
3       40
4       50

### Creating DataFrame from Lists of Lists/Arrays
#### Example 1

In [30]:
# initialize list of lists
data = [['1949', 'Jan', 112], ['1949', 'Feb', 118], ['1949', 'Mar', 132], ['1949', 'Apr', 129], ['1949', 'May', 121]]
 
# Creating the pandas DataFrame with column the columns 'year', 'month','passengers'
flights = pd.DataFrame(data, columns=['year', 'month','passengers'])
 
# Displaying DataFrame
flights.head()

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121

In [31]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        5 non-null      object
 1   month       5 non-null      object
 2   passengers  5 non-null      int64
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

#### Example 2

In [29]:
# initialize list of lists
data = [['tom', 10], ['nick', 15], ['juli', 14]]

# Creating DataFrame ith columns 'Name', 'Age'
df = pd.DataFrame(data, columns=['Name', 'Age'])

# Displaying DataFrame
df.head()

   Name  Age
0   tom   10
1  nick   15
2  juli   14

### Creating DataFrame from List of Tuples

In [23]:
# initialize list of tuples
data = [
    (1, 'Alice', 25),
    (2, 'Bob', 30),
    (3, 'Charlie', 35)
]

# Creating DataFrame with columns 'ID', 'Name', 'Age'
df = pd.DataFrame(data, columns=['ID', 'Name', 'Age'])

# Displaying DataFrame
df.head()

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35

### Creating DataFrame from List of Dictionaries

In [34]:
# Initialize data to lists.
data = [{'a': 1, 'b': 2, 'c': 3},
        {'a': 10, 'b': 20, 'c': 30}]

# Creating DataFrame, keys as columns
df = pd.DataFrame(data)

# Displaying DataFrame
df.head()

    a   b   c
0   1   2   3
1  10  20  30

#### Explanation
* 'a', 'b', and 'c' are the column names.
* The values inside the dictionaries (e.g., 1, 2, 3 in the first dictionary, 10, 20, 30 in the second) represent the actual values for each column in that row.

## From Dictionaries
### Creating DataFrame from dict of narray/lists

To create DataFrame from dict of narray/list, all the narray must be of same length. If index is passed then the length index should be equal to the length of arrays. If no index is passed, then by default, index will be range(n) where n is the array length.

In [6]:

# DataFrame from dict narray / lists

 
# initialize data of lists.
data_m3 = {'Name': ['Tom', 'nick', 'krish', 'jack'],
        'Age': [20, 21, 19, 18]}
 
# Create DataFrame
df_m3 = pd.DataFrame(data_m3)
 
# Print the output.
df_m3

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

# References

* Different ways to create Pandas Dataframe: https://www.geeksforgeeks.org/different-ways-to-create-pandas-dataframe/
* https://sparkbyexamples.com/pandas/pandas-create-dataframe-from-dict-dictionary/